#!/bin/bash
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=5G
#SBATCH --time=10:00:00
#SBATCH --job-name=map_all
#SBATCH --mail-user=xiaoyue.deng@students.unibe.ch
#SBATCH --mail-type=fail,end
#SBATCH --output=/home/xdeng/output_mapping_%j.o
#SBATCH --error=/home/xdeng/error_mapping_%j.e
#SBATCH --array=0-15

# Loading hisat module
module add UHTS/Aligner/hisat/2.2.1

# Index the files directories and names of fasta files as variables
INDEX=/data/courses/rnaseq_course/toxoplasma_de/reference/hisat2
FASTQ=/data/courses/rnaseq_course/toxoplasma_de/reads
NAMES=("SRR7821918" "SRR7821919" "SRR7821920" "SRR7821921" "SRR7821922" "SRR7821937" "SRR7821938" "SRR7821939" "SRR7821949" "SRR7821950" "SRR7821951" "SRR7821952" "SRR7821953" "SRR7821968" "SRR7821969" "SRR7821970")

# Run hisat2 mapping jobs
hisat2 -x $INDEX/Mus_musculus.GRCm39.dna.primary_assembly.fa -1 $FASTQ/${NAMES[$SLURM_ARRAY_TASK_ID]}_1.fastq.gz -2 $FASTQ/${NAMES[$SLURM_ARRAY_TASK_ID]}_2.fastq.gz -S ${NAMES[$SLURM_ARRAY_TASK_ID]}.sam -p 4 --rna-strandness RF
