#!/bin/bash
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=10G
#SBATCH --time=10:00:00
#SBATCH --job-name=sam_index
#SBATCH --mail-user=xiaoyue.deng@students.unibe.ch
#SBATCH --mail-type=fail,end
#SBATCH --output=/home/xdeng/output_mapping_%j.o
#SBATCH --error=/home/xdeng/error_mapping_%j.e
#SBATCH --array=0-16

#Using samtools to index all files. Task performed in the directory containing all the bam files.
samtools index *.sorted.bam
